### ISSUE TITLE
CUDA out of memory

### ISSUE THREAD

**Issue by GoEung** [gaozhitong/SP_guided_Noisy_Label_Seg#3]
I trained model with my custom dataset. After 1 epoch, CUDA error occured.
I changed train batch size to 1 but nothing changed.

```
Warming up dataloader
using pin_memory on device 0
Num per train_loader 562
Num per valid_loader 241
  0%|          | 0/201 [00:00<?, ?it/s][21:03:49.396] train Epoch: 0 loss: 1.122958 dice: 0.047626 
[21:03:49.397] train Epoch: 0 loss: 1.078192 dice: 0.039761 
[21:04:32.062] val Epoch: 0 loss: 1.148290 dice: 0.054719 
[21:04:32.062] val Epoch: 0 loss: 1.079843 dice: 0.040041 
[21:04:32.062] Time till now 0h 25m 5s
[21:04:32.062] Time: 2022-01-03 21:04:32.062486
  0%|          | 1/201 [05:24<18:01:12, 324.36s/it]
Traceback (most recent call last):
  File "C:/Users/Goeun/PycharmProjects/SP_guided_Noisy_Label_Seg/main.py", line 33, in <module>
    nlss_seg.noise_aware_training()
  File "C:\Users\Goeun\PycharmProjects\SP_guided_Noisy_Label_Seg\lib\nlss.py", line 513, in noise_aware_training
    preds_sm = self.super_pixel_smoothing(preds, superpixels)
  File "C:\Users\Goeun\PycharmProjects\SP_guided_Noisy_Label_Seg\lib\nlss.py", line 944, in super_pixel_smoothing
    smooth_value = pixel_map_onehot.sum(dim=(0, 1)) / ((onehot_mask == 1).sum(dim=(0, 1)) + eps)  # (K)
RuntimeError: CUDA out of memory. Tried to allocate 196.00 MiB (GPU 0; 8.00 GiB total capacity; 6.46 GiB already allocated; 0 bytes free; 6.55 GiB reserved in total by PyTorch)

Process finished with exit code 1
```

**Comment by gaozhitong** [comment]
This is caused by the matrix operations in superpixels. To accelerate training, we extend the superpixel map in the one-hot representation, with each dimension demonstrating one cluster id. This truly requires large memory, especially when the number of the segment is large in your superpixel map. Here is something you can try:
1. Generate superpixel maps with a smaller number of segments.
2. Change the code in the 'super_pixel_smoothing' function, use iteration to replace the one-hot matrix operation. 
3. Use another device with larger memory.

**Comment by GoEung** [comment]
> 

Thank you for your answer to my question.
I think this error occured because my GPU memory is small.
I changed the image input size to be smaller, then it works well!
Thank you!
